version: "3"

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    container_name: node_db_1
  backend:
    build: ./backend1
    depends_on:
      - mongo
    ports:
      - 3003:3003
    links:
      - mongo
    container_name: node_backend_1
    environment:
      PRO1_MONGODB_URI: "mongodb://root:example@mongo:27017/admin"
      SECRET: "keyvalue"
      PRO1_PORT: 3003
      KAFKA: 'ds_keyvaluestore_kafka_1:9092'
  frontend:
    build: ./frontend1
    ports: 
      - 3000:3000
    container_name: node_frontend_1
