version: "3"

services:
  backend:
    build: ./backend
    ports:
      - 3003:3003
    environment:
      PRO1_MONGODB_URI: "mongodb+srv://keyvalue:keyvalue@cluster0-aruik.mongodb.net/db1?retryWrites=true&w=majority"
      SECRET: "keyvalue"
      PRO1_PORT: 3003
      KAFKA: 'localhost:9092'
  frontend:
    build: ./frontend
    ports: 
      - 3000:3000
