version: "3"

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  backend:
    build: ./backend2
    depends_on:
      - mongo
    ports:
      - 3004:3004
    links:
      - mongo
    environment:
      PRO1_MONGODB_URI: "mongodb://root:example@mongo:27017/admin"
      SECRET: "keyvalue"
      PRO1_PORT: 3004
      KAFKA: 'ds_keyvaluestore_kafka_1:9092'
  frontend:
    build: ./frontend2
    ports: 
      - 3001:3001
