version: "3"

services:
  mongo1:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    container_name: node_db_1
  backend1:
    build: ./backend1
    depends_on:
      - mongo1
    ports:
      - 3003:3003
    links:
      - mongo1
    container_name: node_backend_1
    environment:
      PRO1_MONGODB_URI: "mongodb://root:example@mongo1:27017/admin"
      SECRET: "keyvalue"
      PRO1_PORT: 3003
      KAFKA: 'ds_kafka:9092'
  frontend1:
    build: ./frontend1
    ports: 
      - 3000:3000
    container_name: node_frontend_1
